version: 0.2

phases:
  build:
    commands:
      - echo "Building the website..."
      - ls -la
  
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync . s3://avery-codebuild-demo --delete --exclude ".git/*" --exclude "buildspec.yml"

artifacts:
  files:
    - '**/*'
